appname = sabaticos_crud
httpport = ${SABATICOS_CRUD_HTTPPORT||8080}
runmode = ${SABATICOS_CRUD_RUNMODE||dev}
autorender = false
copyrequestbody = true
EnableDocs = true
PGuser = ${SABATICOS_CRUD_DB_USER}
PGpass = ${SABATICOS_CRUD_DB_PASS}
PGurls = ${SABATICOS_CRUD_DB_HOST}
PGdb   = ${SABATICOS_CRUD_DB_NAME}
PGschemas = ${SABATICOS_CRUD_SCHEMA}
PGport = ${SABATICOS_CRUD_DB_PORT}

#appname = sabaticos_crud
#httpport = 8080
#runmode = dev
#autorender = false
#copyrequestbody = true
#EnableDocs = true
#
#PGuser = postgres
#PGpass = postgres
#PGurls = localhost
#PGdb   = new_database
#PGschemas = sabatico
#PGport = 5432